name: Build and Push Crypto Docker Images

on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/base/litecoin/docker/**'
      - 'apps/base/bitcoin-core/docker/**'

jobs:
  build:
    runs-on: ubuntu-latest  # Replaced self-hosted with ubuntu-latest

    strategy:
      matrix:
        project:
          - litecoin
          - bitcoin-core
        include:
          - project: litecoin
            path: apps/base/litecoin/docker/**
          - project: bitcoin-core
            path: apps/base/bitcoin-core/docker/**

    steps:
      - name: Check if changes are in the project directory
        if: contains(github.event.pull_request.changed_files, matrix.path)
        run: echo "Changes detected in ${{ matrix.project }} directory."

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from Dockerfile
        id: get_version
        run: |
          VERSION=$(grep '^ARG VERSION=' apps/base/${{ matrix.project }}/docker/Dockerfile | cut -d '=' -f 2)
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ matrix.project }}:${{ env.VERSION }}
          echo "Building and pushing image $IMAGE_NAME"
          docker build -t $IMAGE_NAME apps/base/${{ matrix.project }}/docker
          docker push $IMAGE_NAME

